# GitHub Defaults
safe:               true
lsi:                false
pygments:           true

# Customizations
permalink:          /:month-:day-:year/:title.html
auto:               true
server:             true
server_port:        7580

# Template Data
title:              Hackathons